version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/value_objects
    docker:
      - image: circleci/ruby:2.6.6-node
        environment:
          CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: value_objects-{{ checksum "Gemfile.lock" }}

      # install bundler
      - run: gem install bundler:1.17.3

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: value_objects-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Setup Code Climate Test Reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter

      - run:
          name: Run RSpec
          command: |
            ./tmp/cc-test-reporter before-build
            bundle exec rspec --profile 10 \
                              --out tmp/test-results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            ./tmp/cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
          when: always
      - store_test_results:
          path: tmp/test-results
      - store_artifacts:
          path: tmp/test-results
          destination: test-results